"""Add css_class column to sections table

Revision ID: 20250922_052646
Revises: d8ba4bfce384
Create Date: 2025-09-22 05:26:46.801423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250922_052646'
down_revision = 'd499b730d48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('css_class', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'css_class')
    # ### end Alembic commands ###
