"""Remove social media auto-posting tables

Revision ID: 335d2a55ebe1
Revises: 4292aafbacc9
Create Date: 2025-10-04 20:14:54.906334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '335d2a55ebe1'
down_revision = '4292aafbacc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables in correct order to handle foreign key dependencies
    op.drop_table('social_media_posts')  # Drop first as it has FK to social_media_config
    op.drop_table('auto_posting_queue')  # Drop second
    op.drop_table('social_media_config')  # Drop last (parent table)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_posting_queue',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_retries', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('celery_task_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auto_posting_queue_pkey'))
    )
    op.create_table('social_media_posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform_config_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('post_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('platform_post_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('platform_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shares_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comments_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('posted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['platform_config_id'], ['social_media_config.id'], name=op.f('social_media_posts_platform_config_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('social_media_posts_pkey'))
    )
    op.create_table('social_media_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('api_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('api_secret', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('page_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('auto_post_blog', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('auto_post_events', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('post_template', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hashtags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max_text_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('social_media_config_pkey')),
    sa.UniqueConstraint('platform', name=op.f('social_media_config_platform_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
