"""Add social media auto-posting tables

Revision ID: 4292aafbacc9
Revises: 900014a849d6
Create Date: 2025-10-04 19:07:58.537776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4292aafbacc9'
down_revision = '900014a849d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crm_analysis_records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_analysis_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ankieter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_state', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('previous_state', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('state_change_reason', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('queue_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('queue_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('scheduled_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_processed_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_processing_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('assigned_ankieter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assignment_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('debug_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ankieter_id'], ['users.id'], name=op.f('crm_analysis_records_ankieter_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_ankieter_id'], ['users.id'], name=op.f('crm_analysis_records_assigned_ankieter_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['crm_campaigns.id'], name=op.f('crm_analysis_records_campaign_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], name=op.f('crm_analysis_records_contact_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('crm_analysis_records_pkey'))
    )
    # ### end Alembic commands ###
