"""empty message

Revision ID: 68f474826a4c
Revises: a8a1f342d409
Create Date: 2025-11-22 01:00:33.737724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68f474826a4c'
down_revision = 'a8a1f342d409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop CRM tables only if they exist (they may have been removed already)
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()
    
    crm_tables = ['crm_campaigns', 'crm_calls', 'crm_import_records', 'crm_import_files', 'crm_contacts', 'crm_blacklist']
    
    # Najpierw usuń wszystkie foreign keys, które odnoszą się do tabel CRM
    # Sprawdź wszystkie tabele i usuń foreign keys do tabel CRM
    for table_name in existing_tables:
        try:
            foreign_keys = inspector.get_foreign_keys(table_name)
            for fk in foreign_keys:
                # Sprawdź czy foreign key odnosi się do tabeli CRM
                if fk['referred_table'] in crm_tables:
                    try:
                        with op.batch_alter_table(table_name, schema=None) as batch_op:
                            batch_op.drop_constraint(fk['name'], type_='foreignkey')
                        print(f"✅ Usunięto foreign key {fk['name']} z tabeli {table_name}")
                    except Exception as e:
                        print(f"⚠️ Nie udało się usunąć foreign key {fk['name']} z tabeli {table_name}: {e}")
        except Exception as e:
            print(f"⚠️ Błąd sprawdzania foreign keys dla tabeli {table_name}: {e}")
    
    # Teraz usuń tabele CRM
    for table_name in crm_tables:
        if table_name in existing_tables:
            # Drop indexes first if they exist
            if table_name == 'crm_blacklist':
                try:
                    existing_indexes = [idx['name'] for idx in inspector.get_indexes('crm_blacklist')]
                    if 'ix_crm_blacklist_phone' in existing_indexes:
                        with op.batch_alter_table('crm_blacklist', schema=None) as batch_op:
                            batch_op.drop_index(batch_op.f('ix_crm_blacklist_phone'))
                except Exception:
                    pass  # Index may not exist
            
            try:
                op.drop_table(table_name)
                print(f"✅ Usunięto tabelę {table_name}")
            except Exception as e:
                print(f"⚠️ Błąd usuwania tabeli {table_name}: {e}")
                # Spróbuj z CASCADE
                try:
                    conn.execute(sa.text(f'DROP TABLE IF EXISTS {table_name} CASCADE'))
                    print(f"✅ Usunięto tabelę {table_name} z CASCADE")
                except Exception as e2:
                    print(f"❌ Nie udało się usunąć tabeli {table_name}: {e2}")
        else:
            print(f"⚠️ Tabela {table_name} nie istnieje - pomijam")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blacklisted_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blacklisted_by'], ['users.id'], name=op.f('crm_blacklist_blacklisted_by_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['crm_campaigns.id'], name=op.f('crm_blacklist_campaign_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], name=op.f('crm_blacklist_contact_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('crm_blacklist_pkey'))
    )
    with op.batch_alter_table('crm_blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_blacklist_phone'), ['phone'], unique=False)

    op.create_table('crm_contacts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('crm_contacts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_blacklisted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('call_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_call_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_call_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('source_file', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('import_file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assigned_ankieter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('business_reason', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_ankieter_id'], ['users.id'], name='crm_contacts_assigned_ankieter_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['crm_campaigns.id'], name='crm_contacts_campaign_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_file_id'], ['crm_import_files.id'], name='crm_contacts_import_file_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='crm_contacts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('crm_import_files',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('crm_import_files_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('csv_separator', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('imported_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('import_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('total_rows', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processed_rows', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['crm_campaigns.id'], name='crm_import_files_campaign_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], name='crm_import_files_imported_by_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='crm_import_files_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('crm_import_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('import_file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('row_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('raw_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], name=op.f('crm_import_records_contact_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_file_id'], ['crm_import_files.id'], name=op.f('crm_import_records_import_file_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('crm_import_records_pkey'))
    )
    op.create_table('crm_calls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ankieter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('call_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('call_start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('call_end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('next_call_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('twilio_sid', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_lead_registered', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('queue_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('queue_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('scheduled_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ankieter_id'], ['users.id'], name=op.f('crm_calls_ankieter_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['crm_campaigns.id'], name=op.f('crm_calls_campaign_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], name=op.f('crm_calls_contact_id_fkey')),
    sa.ForeignKeyConstraint(['event_id'], ['event_schedule.id'], name=op.f('crm_calls_event_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('crm_calls_pkey'))
    )
    op.create_table('crm_campaigns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('script_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('crm_campaigns_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('crm_campaigns_pkey'))
    )
    # ### end Alembic commands ###
