"""Add image column to benefit_items

Revision ID: 759870f0f173
Revises: 97010259728c
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759870f0f173'
down_revision = '97010259728c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add image column only if it doesn't exist
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    if 'benefit_items' in existing_tables:
        existing_columns = [col['name'] for col in inspector.get_columns('benefit_items')]
        if 'image' not in existing_columns:
            with op.batch_alter_table('benefit_items', schema=None) as batch_op:
                batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benefit_items', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###

