"""Add CASCADE and SET NULL constraints to user foreign keys

Revision ID: 8a4291b8153b
Revises: af25e20522fc
Create Date: 2025-09-19 03:59:51.601363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4291b8153b'
down_revision = 'af25e20522fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('blog_comments_moderated_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['moderated_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('blog_posts_author_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('crm_blacklist', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('crm_blacklist_blacklisted_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['blacklisted_by'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('crm_calls', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('crm_calls_ankieter_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['ankieter_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('crm_contacts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('crm_contacts_assigned_ankieter_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['assigned_ankieter_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('crm_import_files', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('crm_import_files_imported_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['imported_by'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('password_reset_tokens_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('seo_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('seo_settings_created_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('user_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_history_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_logs_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_logs_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_history_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('seo_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('seo_settings_created_by_fkey'), 'users', ['created_by'], ['id'])

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('password_reset_tokens_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('crm_import_files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('crm_import_files_imported_by_fkey'), 'users', ['imported_by'], ['id'])

    with op.batch_alter_table('crm_contacts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('crm_contacts_assigned_ankieter_id_fkey'), 'users', ['assigned_ankieter_id'], ['id'])

    with op.batch_alter_table('crm_calls', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('crm_calls_ankieter_id_fkey'), 'users', ['ankieter_id'], ['id'])

    with op.batch_alter_table('crm_blacklist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('crm_blacklist_blacklisted_by_fkey'), 'users', ['blacklisted_by'], ['id'])

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('blog_posts_author_id_fkey'), 'users', ['author_id'], ['id'])

    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('blog_comments_moderated_by_fkey'), 'users', ['moderated_by'], ['id'])

    # ### end Alembic commands ###
