"""Add Twilio fields to Call model

Revision ID: 900014a849d6
Revises: c1d2e3f4g5h6
Create Date: 2025-10-03 09:16:58.010430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900014a849d6'
down_revision = 'c1d2e3f4g5h6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('twilio_sid', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_calls', schema=None) as batch_op:
        batch_op.drop_column('twilio_sid')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
