"""add_show_on_post_card_to_social_links

Revision ID: 9356897bb38f
Revises: 759870f0f173
Create Date: 2025-11-16 03:28:56.301071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9356897bb38f'
down_revision = '759870f0f173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if tables exist before creating them (for production compatibility)
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    if 'crm_import_files' not in existing_tables:
        op.create_table('crm_import_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('csv_separator', sa.String(length=5), nullable=True),
    sa.Column('imported_by', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('import_status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('processed_rows', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['crm_campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    
    if 'crm_blacklist' not in existing_tables:
        op.create_table('crm_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('blacklisted_by', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blacklisted_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['crm_campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('crm_blacklist', schema=None) as batch_op:
            # Check if index exists before creating
            indexes = [idx['name'] for idx in inspector.get_indexes('crm_blacklist')] if 'crm_blacklist' in existing_tables else []
            if 'ix_crm_blacklist_phone' not in indexes:
                batch_op.create_index(batch_op.f('ix_crm_blacklist_phone'), ['phone'], unique=False)
    
    if 'crm_calls' not in existing_tables:
        op.create_table('crm_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('ankieter_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('call_date', sa.DateTime(), nullable=False),
    sa.Column('call_start_time', sa.DateTime(), nullable=True),
    sa.Column('call_end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_call_date', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('twilio_sid', sa.String(length=100), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('is_lead_registered', sa.Boolean(), nullable=True),
    sa.Column('queue_status', sa.String(length=20), nullable=True),
    sa.Column('queue_type', sa.String(length=20), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ankieter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['crm_campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event_schedule.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    
    if 'crm_import_records' not in existing_tables:
        op.create_table('crm_import_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_file_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_file_id'], ['crm_import_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Drop tables only if they exist
    if 'crm_v2_call_sessions' in existing_tables:
        with op.batch_alter_table('crm_v2_call_sessions', schema=None) as batch_op:
            indexes = [idx['name'] for idx in inspector.get_indexes('crm_v2_call_sessions')]
            if 'ix_crm_v2_call_sessions_ankieter_id' in indexes:
                batch_op.drop_index(batch_op.f('ix_crm_v2_call_sessions_ankieter_id'))
            if 'ix_crm_v2_call_sessions_record_id' in indexes:
                batch_op.drop_index(batch_op.f('ix_crm_v2_call_sessions_record_id'))
        op.drop_table('crm_v2_call_sessions')
    
    if 'crm_call_sessions' in existing_tables:
        with op.batch_alter_table('crm_call_sessions', schema=None) as batch_op:
            indexes = [idx['name'] for idx in inspector.get_indexes('crm_call_sessions')]
            if 'ix_crm_call_sessions_agent_id' in indexes:
                batch_op.drop_index(batch_op.f('ix_crm_call_sessions_agent_id'))
            if 'ix_crm_call_sessions_business_result' in indexes:
                batch_op.drop_index(batch_op.f('ix_crm_call_sessions_business_result'))
            if 'ix_crm_call_sessions_campaign_id' in indexes:
                batch_op.drop_index(batch_op.f('ix_crm_call_sessions_campaign_id'))
            if 'ix_crm_call_sessions_contact_id' in indexes:
                batch_op.drop_index(batch_op.f('ix_crm_call_sessions_contact_id'))
            if 'ix_crm_call_sessions_created_at' in indexes:
                batch_op.drop_index(batch_op.f('ix_crm_call_sessions_created_at'))
            if 'ix_crm_call_sessions_start_time' in indexes:
                batch_op.drop_index(batch_op.f('ix_crm_call_sessions_start_time'))
            if 'ix_crm_call_sessions_status' in indexes:
                batch_op.drop_index(batch_op.f('ix_crm_call_sessions_status'))
            if 'ix_crm_call_sessions_zadarma_call_id' in indexes:
                batch_op.drop_index(batch_op.f('ix_crm_call_sessions_zadarma_call_id'))
        op.drop_table('crm_call_sessions')
    
    if 'task_queue' in existing_tables:
        with op.batch_alter_table('task_queue', schema=None) as batch_op:
            indexes = [idx['name'] for idx in inspector.get_indexes('task_queue')]
            if 'ix_task_queue_created_at' in indexes:
                batch_op.drop_index(batch_op.f('ix_task_queue_created_at'))
            if 'ix_task_queue_priority' in indexes:
                batch_op.drop_index(batch_op.f('ix_task_queue_priority'))
            if 'ix_task_queue_status' in indexes:
                batch_op.drop_index(batch_op.f('ix_task_queue_status'))
            if 'ix_task_queue_task_name' in indexes:
                batch_op.drop_index(batch_op.f('ix_task_queue_task_name'))
        op.drop_table('task_queue')
    
    if 'crm_v2_records' in existing_tables:
        with op.batch_alter_table('crm_v2_records', schema=None) as batch_op:
            indexes = [idx['name'] for idx in inspector.get_indexes('crm_v2_records')]
            if 'ix_crm_v2_records_campaign_id' in indexes:
                batch_op.drop_index(batch_op.f('ix_crm_v2_records_campaign_id'))
            if 'ix_crm_v2_records_phone' in indexes:
                batch_op.drop_index(batch_op.f('ix_crm_v2_records_phone'))
        op.drop_table('crm_v2_records')
    
    # Drop crm_v2_campaigns after dropping dependent table crm_v2_records
    if 'crm_v2_campaigns' in existing_tables:
        op.drop_table('crm_v2_campaigns')
    with op.batch_alter_table('crm_campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_crm_campaigns_created_at'))
        batch_op.drop_index(batch_op.f('ix_crm_campaigns_is_active'))
        batch_op.drop_constraint(batch_op.f('crm_campaigns_created_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('crm_contacts', schema=None) as batch_op:
        # Add phone column as nullable first, then migrate data, then make it NOT NULL
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('source_file', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('import_file_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('assigned_ankieter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('business_reason', sa.String(length=50), nullable=True))
    
    # Migrate data from phone_number to phone for existing records
    op.execute("""
        UPDATE crm_contacts 
        SET phone = phone_number 
        WHERE phone_number IS NOT NULL AND phone IS NULL
    """)
    
    # Set default value for records that still have NULL phone
    op.execute("""
        UPDATE crm_contacts 
        SET phone = '' 
        WHERE phone IS NULL
    """)
    
    # Now make phone NOT NULL
    with op.batch_alter_table('crm_contacts', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('_campaign_phone_uc'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_crm_contacts_assigned_to_id'))
        batch_op.drop_index(batch_op.f('ix_crm_contacts_call_attempts'))
        batch_op.drop_index(batch_op.f('ix_crm_contacts_callback_datetime'))
        batch_op.drop_index(batch_op.f('ix_crm_contacts_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_crm_contacts_created_at'))
        batch_op.drop_index(batch_op.f('ix_crm_contacts_is_active'))
        batch_op.drop_index(batch_op.f('ix_crm_contacts_is_blacklisted'))
        batch_op.drop_index(batch_op.f('ix_crm_contacts_last_call_date'))
        batch_op.drop_index(batch_op.f('ix_crm_contacts_next_call_scheduled_at'))
        batch_op.drop_constraint(batch_op.f('crm_contacts_assigned_to_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('crm_contacts_campaign_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'crm_import_files', ['import_file_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['assigned_ankieter_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'crm_campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('assigned_to_id')
        batch_op.drop_column('callback_datetime')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('next_call_scheduled_at')

    with op.batch_alter_table('social_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_on_post_card', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_links', schema=None) as batch_op:
        batch_op.drop_column('show_on_post_card')

    with op.batch_alter_table('crm_contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_call_scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('callback_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('assigned_to_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('crm_contacts_campaign_id_fkey'), 'crm_campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('crm_contacts_assigned_to_id_fkey'), 'users', ['assigned_to_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_crm_contacts_next_call_scheduled_at'), ['next_call_scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_contacts_last_call_date'), ['last_call_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_contacts_is_blacklisted'), ['is_blacklisted'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_contacts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_contacts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_contacts_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_contacts_callback_datetime'), ['callback_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_contacts_call_attempts'), ['call_attempts'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_contacts_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('_campaign_phone_uc'), ['campaign_id', 'phone_number'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('business_reason')
        batch_op.drop_column('assigned_ankieter_id')
        batch_op.drop_column('tags')
        batch_op.drop_column('import_file_id')
        batch_op.drop_column('source_file')
        batch_op.drop_column('phone')

    with op.batch_alter_table('crm_campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('crm_campaigns_created_by_id_fkey'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_crm_campaigns_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_campaigns_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('created_by')

    op.create_table('crm_v2_records',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('crm_v2_records_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_ankieter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_blacklisted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('call_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_call_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_call_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_ankieter_id'], ['users.id'], name='crm_v2_records_assigned_ankieter_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['crm_v2_campaigns.id'], name='crm_v2_records_campaign_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='crm_v2_records_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('crm_v2_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_v2_records_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_v2_records_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('task_queue',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('task_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'RETRYING', name='taskstatus'), autoincrement=False, nullable=True),
    sa.Column('priority', postgresql.ENUM('LOW', 'NORMAL', 'HIGH', 'URGENT', name='taskpriority'), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_retries', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('task_queue_pkey'))
    )
    with op.batch_alter_table('task_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_queue_task_name'), ['task_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_queue_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_queue_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_queue_created_at'), ['created_at'], unique=False)

    # Create crm_v2_campaigns first (before crm_v2_records which depends on it)
    op.create_table('crm_v2_campaigns',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('crm_v2_campaigns_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('script_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='crm_v2_campaigns_created_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='crm_v2_campaigns_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('crm_call_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('business_result', postgresql.ENUM('pending', 'answered', 'no_answer', 'busy', 'failed', 'lead', 'rejection', 'callback', 'wrong_number', 'cancelled', 'blacklisted', name='businessresult'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('next_call_scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('zadarma_call_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name=op.f('crm_call_sessions_agent_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['crm_campaigns.id'], name=op.f('crm_call_sessions_campaign_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], name=op.f('crm_call_sessions_contact_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('crm_call_sessions_pkey'))
    )
    with op.batch_alter_table('crm_call_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_call_sessions_zadarma_call_id'), ['zadarma_call_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_crm_call_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_call_sessions_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_call_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_call_sessions_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_call_sessions_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_call_sessions_business_result'), ['business_result'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_call_sessions_agent_id'), ['agent_id'], unique=False)

    op.create_table('crm_v2_call_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ankieter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('business_result', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('business_result_source', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('call_start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('call_end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('zadarma_call_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ankieter_id'], ['users.id'], name=op.f('crm_v2_call_sessions_ankieter_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['crm_v2_campaigns.id'], name=op.f('crm_v2_call_sessions_campaign_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['record_id'], ['crm_v2_records.id'], name=op.f('crm_v2_call_sessions_record_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('crm_v2_call_sessions_pkey'))
    )
    with op.batch_alter_table('crm_v2_call_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_v2_call_sessions_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_v2_call_sessions_ankieter_id'), ['ankieter_id'], unique=False)

    op.drop_table('crm_import_records')
    op.drop_table('crm_calls')
    with op.batch_alter_table('crm_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_blacklist_phone'))

    op.drop_table('crm_blacklist')
    op.drop_table('crm_import_files')
    # ### end Alembic commands ###
