"""add_show_on_post_card_to_social_links

Revision ID: 9356897bb38f
Revises: c1d2e3f4g5h6
Create Date: 2025-11-16 03:28:56.301071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9356897bb38f'
down_revision = 'c1d2e3f4g5h6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: All CRM-related operations removed - CRM module has been removed from the system
    # This migration now only handles the main purpose: adding show_on_post_card to social_links
    
    # Check if tables exist before modifying (for production compatibility)
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    # Add show_on_post_card column to social_links (this is the main purpose of this migration)
    if 'social_links' in existing_tables:
        social_links_columns = [col['name'] for col in inspector.get_columns('social_links')]
        if 'show_on_post_card' not in social_links_columns:
            with op.batch_alter_table('social_links', schema=None) as batch_op:
                batch_op.add_column(sa.Column('show_on_post_card', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: All CRM-related operations removed - CRM module has been removed from the system
    # This migration now only handles the main purpose: removing show_on_post_card from social_links
    
    # Check if tables exist before modifying (for production compatibility)
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    if 'social_links' in existing_tables:
        social_links_columns = [col['name'] for col in inspector.get_columns('social_links')]
        if 'show_on_post_card' in social_links_columns:
            with op.batch_alter_table('social_links', schema=None) as batch_op:
                batch_op.drop_column('show_on_post_card')

    # ### end Alembic commands ###
