"""add_admin_theme_to_user

Revision ID: a8a1f342d409
Revises: 6b1ed6bca085
Create Date: 2025-11-22 00:55:51.025792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a1f342d409'
down_revision = '6b1ed6bca085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_theme', sa.String(length=20), nullable=True, server_default='light'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('admin_theme')
    # ### end Alembic commands ###
