"""Add CRM campaigns system

Revision ID: b8e4fb2773cf
Revises: 1ba750811cb7
Create Date: 2025-10-02 22:56:52.062206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e4fb2773cf'
down_revision = '1ba750811cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'crm_campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('crm_contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'crm_campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('crm_import_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'crm_campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_import_files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('campaign_id')

    with op.batch_alter_table('crm_contacts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('campaign_id')

    with op.batch_alter_table('crm_calls', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('campaign_id')

    # ### end Alembic commands ###
