"""Add CRM campaigns system

Revision ID: b8e4fb2773cf
Revises: 1ba750811cb7
Create Date: 2025-10-02 22:56:52.062206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e4fb2773cf'
down_revision = '1ba750811cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if tables exist before modifying (CRM tables may have been removed)
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    if 'crm_calls' in existing_tables:
        existing_columns = [col['name'] for col in inspector.get_columns('crm_calls')]
        with op.batch_alter_table('crm_calls', schema=None) as batch_op:
            if 'campaign_id' not in existing_columns:
                batch_op.add_column(sa.Column('campaign_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key(None, 'crm_campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    
    if 'crm_contacts' in existing_tables:
        existing_columns = [col['name'] for col in inspector.get_columns('crm_contacts')]
        with op.batch_alter_table('crm_contacts', schema=None) as batch_op:
            if 'campaign_id' not in existing_columns:
                batch_op.add_column(sa.Column('campaign_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key(None, 'crm_campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    
    if 'crm_import_files' in existing_tables:
        existing_columns = [col['name'] for col in inspector.get_columns('crm_import_files')]
        with op.batch_alter_table('crm_import_files', schema=None) as batch_op:
            if 'campaign_id' not in existing_columns:
                batch_op.add_column(sa.Column('campaign_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key(None, 'crm_campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if tables exist before modifying (CRM tables may have been removed)
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    if 'crm_import_files' in existing_tables:
        with op.batch_alter_table('crm_import_files', schema=None) as batch_op:
            batch_op.drop_constraint(None, type_='foreignkey')
            batch_op.drop_column('campaign_id')

    if 'crm_contacts' in existing_tables:
        with op.batch_alter_table('crm_contacts', schema=None) as batch_op:
            batch_op.drop_constraint(None, type_='foreignkey')
            batch_op.drop_column('campaign_id')

    if 'crm_calls' in existing_tables:
        with op.batch_alter_table('crm_calls', schema=None) as batch_op:
            batch_op.drop_constraint(None, type_='foreignkey')
            batch_op.drop_column('campaign_id')

    # ### end Alembic commands ###
