"""Add CASCADE delete to ImportRecord contact_id foreign key

Revision ID: b8f996496580
Revises: dd80820288f3
Create Date: 2025-10-08 04:02:13.092470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f996496580'
down_revision = 'dd80820288f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table exists before modifying (CRM tables may have been removed)
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    if 'crm_import_records' in existing_tables:
        with op.batch_alter_table('crm_import_records', schema=None) as batch_op:
            # Check if constraint exists before dropping
            existing_fks = [fk['name'] for fk in inspector.get_foreign_keys('crm_import_records')]
            if 'crm_import_records_contact_id_fkey' in existing_fks:
                batch_op.drop_constraint(batch_op.f('crm_import_records_contact_id_fkey'), type_='foreignkey')
            batch_op.create_foreign_key(None, 'crm_contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    else:
        print("⚠️ Tabela crm_import_records nie istnieje - pomijam migrację")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table exists before modifying (CRM tables may have been removed)
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    if 'crm_import_records' in existing_tables:
        with op.batch_alter_table('crm_import_records', schema=None) as batch_op:
            batch_op.drop_constraint(None, type_='foreignkey')
            batch_op.create_foreign_key(batch_op.f('crm_import_records_contact_id_fkey'), 'crm_contacts', ['contact_id'], ['id'])

    # ### end Alembic commands ###
