"""Add CASCADE delete to ImportRecord contact_id foreign key

Revision ID: b8f996496580
Revises: 900014a849d6
Create Date: 2025-10-08 04:02:13.092470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f996496580'
down_revision = '900014a849d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_import_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('crm_import_records_contact_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'crm_contacts', ['contact_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_import_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('crm_import_records_contact_id_fkey'), 'crm_contacts', ['contact_id'], ['id'])

    # ### end Alembic commands ###
