"""Update blacklist model

Revision ID: c1d2e3f4g5h6
Revises: b8e4fb2773cf
Create Date: 2025-10-03 03:40:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d2e3f4g5h6'
down_revision = 'b8e4fb2773cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_blacklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'crm_campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_constraint('crm_blacklist_phone_key', type_='unique')
        batch_op.create_index('ix_crm_blacklist_phone', ['phone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_blacklist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_crm_blacklist_phone')
        batch_op.drop_column('campaign_id')
        batch_op.create_unique_constraint('crm_blacklist_phone_key', ['phone'])

    # ### end Alembic commands ###
