"""add_event_url_field_to_events

Revision ID: c3202b60b9f3
Revises: c46ca71949f5
Create Date: 2025-10-20 22:29:38.838916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3202b60b9f3'
down_revision = 'c46ca71949f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_schedule', schema=None) as batch_op:
        batch_op.drop_column('event_url')

    # ### end Alembic commands ###
