"""add_description_column_to_email_campaigns

Revision ID: c46ca71949f5
Revises: 325b67795620
Create Date: 2025-10-13 19:53:34.846252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c46ca71949f5'
down_revision = '325b67795620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_calls_campaign_id'))

    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_logs_campaign_id'))

    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_queue_campaign_id'))

    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('event_registrations_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('event_registrations_event_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'event_schedule', ['event_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('password_reset_tokens_token_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token'))
        batch_op.create_unique_constraint(batch_op.f('password_reset_tokens_token_key'), ['token'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('token',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('event_registrations_event_id_fkey'), 'event_schedule', ['event_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('event_registrations_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_queue_campaign_id'), ['campaign_id'], unique=False)

    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_logs_campaign_id'), ['campaign_id'], unique=False)

    with op.batch_alter_table('crm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_calls_campaign_id'), ['campaign_id'], unique=False)

    # ### end Alembic commands ###
