"""Add message_id to EmailLog for webhook tracking

Revision ID: dd80820288f3
Revises: 1741a81db96b
Create Date: 2025-10-01 15:34:52.045519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd80820288f3'
down_revision = '1741a81db96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_column('message_id')

    # ### end Alembic commands ###
