"""Add email_reminders table for tracking sent reminder emails

Revision ID: 0e71010ff0ce
Revises: 20250922_052646
Create Date: 2025-09-23 16:04:03.027443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e71010ff0ce'
down_revision = '20250922_052646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Tabela już istnieje z poprawnym constraint 'uq_email_reminder'
    # Nie trzeba nic robić - tabela jest już poprawnie skonfigurowana
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Tabela już istnieje - nie ma co cofać
    pass
    # ### end Alembic commands ###
