"""Add email_reminders table for tracking sent reminder emails

Revision ID: 0e71010ff0ce
Revises: 20250922_052646
Create Date: 2025-09-23 16:04:03.027443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e71010ff0ce'
down_revision = '20250922_052646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_reminders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('email_reminders_user_id_event_id_reminder_type_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_email_reminders_user_event'))
        batch_op.create_unique_constraint('uq_email_reminder', ['user_id', 'event_id', 'reminder_type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_reminders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_email_reminder', type_='unique')
        batch_op.create_index(batch_op.f('idx_email_reminders_user_event'), ['user_id', 'event_id', 'reminder_type'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('email_reminders_user_id_event_id_reminder_type_key'), ['user_id', 'event_id', 'reminder_type'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
