"""Add account_type, event_id, group_id to User model

Revision ID: 174ac7b3976b
Revises: 95eededfd71e
Create Date: 2025-09-19 00:32:37.490830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174ac7b3976b'
down_revision = '95eededfd71e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_account_type'), ['account_type'], unique=False)
        batch_op.create_foreign_key(None, 'event_schedule', ['event_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_groups', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_account_type'))
        batch_op.drop_column('group_id')
        batch_op.drop_column('event_id')
        batch_op.drop_column('account_type')

    # ### end Alembic commands ###
