"""Add duplicate prevention to email queue

Revision ID: 3b231ed058fc
Revises: 8be69bfdcb53
Create Date: 2025-09-24 21:43:30.676035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b231ed058fc'
down_revision = '8be69bfdcb53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add columns as nullable first
    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('duplicate_check_key', sa.String(length=255), nullable=True))
    
    # Step 2: Generate content_hash for existing records (outside batch_alter_table)
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE email_queue 
        SET content_hash = MD5(CONCAT(recipient_email, '|', subject, '|', COALESCE(html_content, ''), '|', COALESCE(text_content, '')))
        WHERE content_hash IS NULL
    """))
    
    # Step 3: Make content_hash non-nullable and create indexes
    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.alter_column('content_hash', nullable=False)
        
        # Create indexes for duplicate detection
        batch_op.create_index(batch_op.f('ix_email_queue_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_queue_duplicate_check_key'), ['duplicate_check_key'], unique=False)
        batch_op.create_index('ix_email_queue_duplicate_pending', ['recipient_email', 'subject', 'status'], unique=False)
        batch_op.create_index('ix_email_queue_campaign_duplicate', ['recipient_email', 'campaign_id', 'content_hash'], unique=False)
        batch_op.create_index('ix_email_queue_custom_key', ['duplicate_check_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.drop_index('ix_email_queue_custom_key')
        batch_op.drop_index('ix_email_queue_campaign_duplicate')
        batch_op.drop_index('ix_email_queue_duplicate_pending')
        batch_op.drop_index(batch_op.f('ix_email_queue_duplicate_check_key'))
        batch_op.drop_index(batch_op.f('ix_email_queue_content_hash'))
        batch_op.drop_column('duplicate_check_key')
        batch_op.drop_column('content_hash')

    # ### end Alembic commands ###
