"""Add event_id to UserGroup model

Revision ID: 61639eea677a
Revises: b44b982d3dbe
Create Date: 2025-09-19 01:01:21.428466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61639eea677a'
down_revision = 'b44b982d3dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'event_schedule', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
