"""Add recipient_email, recipient_name, template_name, and priority fields to email_queue

Revision ID: 8be69bfdcb53
Revises: 0e71010ff0ce
Create Date: 2025-09-23 16:39:32.282920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be69bfdcb53'
down_revision = '0e71010ff0ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns as nullable first
    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('recipient_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('template_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))
    
    # Copy data from old columns to new columns
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE email_queue SET recipient_email = to_email WHERE recipient_email IS NULL"))
    connection.execute(sa.text("UPDATE email_queue SET recipient_name = to_name WHERE recipient_name IS NULL"))
    connection.execute(sa.text("UPDATE email_queue SET priority = 2 WHERE priority IS NULL"))
    
    # Now make recipient_email NOT NULL
    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.alter_column('recipient_email', nullable=False)
        batch_op.drop_column('to_name')
        batch_op.drop_column('to_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('to_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('priority')
        batch_op.drop_column('template_name')
        batch_op.drop_column('recipient_name')
        batch_op.drop_column('recipient_email')

    # ### end Alembic commands ###
