"""Add blog columns to MenuItem

Revision ID: 95eededfd71e
Revises: bd1c9d1c9413
Create Date: 2025-09-18 22:13:22.033045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95eededfd71e'
down_revision = 'bd1c9d1c9413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blog_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('blog', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('blog')
        batch_op.drop_column('blog_url')

    # ### end Alembic commands ###
