"""Add EmailReminder model and Celery tasks

Revision ID: d1fe377fc0cc
Revises: 3b231ed058fc
Create Date: 2025-09-25 03:09:20.132753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1fe377fc0cc'
down_revision = '3b231ed058fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_registrations')
    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'event_schedule', ['event_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('account_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
        batch_op.create_index(batch_op.f('ix_users_account_type'), ['account_type'], unique=False)
        batch_op.create_foreign_key(None, 'user_groups', ['group_id'], ['id'])
        batch_op.create_foreign_key(None, 'event_schedule', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_account_type'))
        batch_op.alter_column('account_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))

    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('event_registrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('wants_club_news', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('notification_preferences', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_schedule.id'], name=op.f('event_registrations_event_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('event_registrations_pkey'))
    )
    # ### end Alembic commands ###
